In [7]:
import networkx as nx
import seaborn as sns
import numpy as np
import scipy as sp
import pandas as pd
from collections import defaultdict

In [8]:
df = pd.read_csv('data/valuesMatrix.csv')
df.columns
df.head(10)

             name  lvl
0            none    1
1          little    2
2            some    3
3            more    4
4             all    5
5      ACCEPTANCE    2
6     ACHIEVEMENT    3
7       ADVENTURE    4
8             ART    4
9  ATTRACTIVENESS    4

In [9]:
nameDict = df['name']
nameDict[0]
df = df.drop('name',axis=1)
# # range of lvls 1-5
df[df['lvl'] < 5] -= 1
# newCol = df['lvl'].to_numpy()
# newCol = [[x] for x in newCol]
# df['lvl'] = newCol
df.head(10)

   lvl
0    0
1    1
2    2
3    3
4    5
5    1
6    2
7    3
8    3
9    3

In [44]:

def createAdjList(df):
    adjDictScale = defaultdict(list)
    adjDictValue = defaultdict(list)
    #DICT
    for idx, name in enumerate(df):
        # connect scale nodes to create complete graph
        if idx < 4:
            adjDictValue[idx] = (idx+1, idx+1, name)
       # fully connected graph
        elif idx == 5:
             adjDictValue[idx] = (idx+1, 0, name) 
        else:
            adjDictValue[idx] = (idx+1,df.iloc[idx][0], name)
            
    return (adjDictValue,adjDictScale)


def createScaleAndValue(df):
    
    adjDictScale = defaultdict(list)
    adjDictValue = defaultdict(list)
    #DICT
    for idx, name in enumerate(df):
        # connect scale nodes to create complete graph
        if idx < 4:
            adjDictScale[idx] = (idx+1, idx+1, name)
       # fully connected graph
        elif idx == 5:
             adjDictScale[idx] = (idx+1, 0, name) 
        else:
            adjDictValue[idx] = (idx+1,df.iloc[idx][0], name)
            
    return (adjDictValue,adjDictScale)

def bipartite(u,v,edges):
    bi = nx.Graph()
    bi.add_nodes_from(u, bipartite=0)
    bi.add_nodes_from(v, bipartite=1)
    bi.add_edges_from(edges)
    return bi

In [49]:
# Call G1
g1_adjDictValue, g1_adjDictScale = createAdjList(df)
g2_adjDictValue, g2_adjDictScale = createScaleAndValue(df)

g1_adjDictValue

defaultdict(list, {0: (1, 1, 'lvl')})

In [ ]:
# # scale
# u = [x for x in range(4)]
# v = [x for x in range(4,104)]
# edges = [(edge,scale) for edge,scale in enumerate(g2_adjDictValue)]

# biGraph = bipartite(u,v,edges)


# Array

# adjListScale = list()
# adjListValue = list()

# for idx, name in enumerate(nameDict):
#     if idx < 5:
#         adjListScale.append( (idx ,df.iloc[idx][0]) )
#     else:
#         adjListValue.append((idx, df.iloc[idx][0]))